### ISSUE TITLE
Remove github deployment code

### ISSUE THREAD

**Issue by tocttou** [Cloud-CV/cvfy-frontend#18]

**Comment by tocttou** [comment]
There is a lot of code not in use currently in the repository. This code is for deployments supposed to work from GitHub directly and is far behind the other deployment method in terms of updates. This code is mostly in the folders that have "GitHub" in the name. Anyone fixing this should remove that code and take care of removing the unwanted imports from the app, if any.

**Comment by anweshknayak** [comment]
@tocttou on it. thanks

**Comment by tocttou** [comment]
a0d72e8cd98ab5e0d6627b79925575284c40f448 solves this.
