### ISSUE TITLE
Build a demo for Image Captioning

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/cvfy-frontend#28]
Try building a demo for image captioning using the tensorflow code provide here: 
~https://github.com/jazzsaxmafia/show_attend_and_tell.tensorflow~

EDIT (@abhshkdz): This implementation seems to be better maintained and easier to work with — https://github.com/yunjey/show-attend-and-tell-tensorflow

**Comment by ccpandhare** [comment]
Can I try this?

**Comment by dexter1691** [comment]
Sure! Please keep us updated!

**Comment by AvaisP** [comment]
Hey, @dexter1691 
Is this issue still open? I'd like to start working on this

**Comment by deshraj** [comment]
Yeah @AvaisP, it's open. Please let us know if you have issues.

**Comment by AvaisP** [comment]
Yes sure. I'm working on it!

**Comment by AvaisP** [comment]
Hey, @dexter1691 
Have you worked with https://github.com/yunjey/show-attend-and-tell-tensorflow? It needs some 30GB of data. If you have already trained the data, it would be great if you could upload the contents of the 'data' directory after training.

**Comment by abhshkdz** [comment]
I'm surprised they haven't released a pre-trained checkpoint. I just opened an issue: https://github.com/yunjey/show-attend-and-tell-tensorflow/issues/18, keep a watch, I hope he responds soon.

**Comment by dexter1691** [comment]
https://github.com/jazzsaxmafia/show_and_tell.tensorflow
This code has a pretrained model. It's the older paper, but image captioning task nevertheless. You can try this if you want.

**Comment by AvaisP** [comment]
@abhshkdz thanks I'll keep checking the issue out. Until then I'll start working on the other repository
@dexter1691

**Comment by AvaisP** [comment]
@dexter1691 https://github.com/jazzsaxmafia/show_and_tell.tensorflow is buggy. I have been trying to debug the same issue as https://github.com/jazzsaxmafia/show_and_tell.tensorflow/issues/13 . Haven't had much success. What should I do?

**Comment by AvaisP** [comment]
Hey @dexter1691 
I've created a demo at https://github.com/AvaisP/cvfy-show-and-tell 
Here is the input and output using a random picture found on google.
![screenshot from 2017-03-08 19-18-21](https://cloud.githubusercontent.com/assets/15157205/23706640/089b6282-0435-11e7-8f8d-a85b3b519589.png)
![screenshot from 2017-03-08 19-18-40](https://cloud.githubusercontent.com/assets/15157205/23706645/0b58d748-0435-11e7-9123-11c657ab2266.png)

**Comment by deshraj** [comment]
@AvaisP This looks great. :) 

It looks like we have to modify the components really soon so that the final demo should look more fancy.

**Comment by AvaisP** [comment]
@deshraj Yes we should. At the same time, we should ensure that in trying to make it look fancy, the web app is still easy to use. Anyway, that's a long way :joy: . For now, do we consider this issue to be closed? :smile:

**Comment by punarvasu510** [comment]
Hey @dexter1691 @deshraj Will the issue be closed? Is there anything left in this? I'd like to contribute.

**Comment by AvaisP** [comment]
Hey @punarvasu510 
I'd suggest you work on another issue as this one is done! :smile:
