### ISSUE TITLE
Add the ability to cache intermediate output

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/cvfy-frontend#33]
Sometimes, the demo requires multiple interactions with the user. For example, in Visual Question Answering, a user can ask multiple questions for the same image. We can reuse the image features for a particular session to save some time and return the results quickly. 
Similarly, for sequential dialog, the results from the history should be saved.

Currently we don't have the ability to save these intermediate results. To implement this feature, we can use a session identifier to store the results on the backend. If users can get the session identifier then it will be easy for them to cache those results on the backend.

**Comment by tocttou** [comment]
Would it be better to ask the demo creator about what they would like to be cached for the user. This can be done via a new API in origami(cvfy).py ... something like:

```
if not origami.get_from_cache("user_session_id", "object_id"):
  # do xyz operation
  origami.save_to_cache("user_session", "object_id", object_data);
```

**Comment by dexter1691** [comment]
Yes. This should work.

**Comment by tocttou** [comment]
Cloud-CV/cvfy-lib@f466b45 adds support for Text Array caching and internal functions to support caching for images also. Will work on adding image caching support now.

API:

`cvfy.checkIfCachedResultsExist`: `() => boolean`
`cvfy.loadTextArrayFromCache`: `() => array`
`cvfy.saveTextArrayToCache`: `(text_array) => None`
`cvfy.getUniqueCacheId()`: `() => unique_id` (internal function)

Example:

```
if cvfy.checkIfCachedResultsExist():
  cvfy.sendTextArray(
    cvfy.loadTextArrayFromCache()
  )
else:
  #some-computation
  cvfy.saveTextArrayToCache()
```

The user need not worry about the cache ID. Each combination of input (image/image+text/text) has a unique fingerprint which is used as the cache ID automatically internally.

**Comment by tocttou** [comment]
Cloud-CV/cvfy-lib@57b7790 adds support for full caching.

Demo: https://zippy.gfycat.com/FilthyRedHoneycreeper.webm

Sample code: https://gist.github.com/tocttou/669c516fd8d4fd0934d188c4f3b5ad39

**Comment by kakshay21** [comment]
can i work on this?@dexter1691 @tocttou

**Comment by tocttou** [comment]
@kakshay21 This has already been done.
