### ISSUE TITLE
Upload media from Dropbox

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/cvfy-frontend#34]
Apart from uploading files locally, we want to support adding media through Dropbox / Google Drive / URL.

**Comment by AvaisP** [comment]
@dexter1691 @tocttou  I've managed to get the dropbox url of the image into the web app. I am a little confused about what to do next. When we upload a local image, the onDrop() function gets a file object with. However, if I create a File object using the dropbox url, it doesn't work. Any tips on what I should be doing?

**Comment by tocttou** [comment]
@AvaisP there is no direct way to do this but you can combine the Blob and File APIs :)

```
const file = new File([new Blob(['http://i.imgur.com/8lIYpog.png'], { type: 'file' })], 'filename.png');
```

Once you have the `file` (Object-Type: File), you can pick up the workflow from [inputcomponents/ImageInput/SingleInput.js](https://github.com/Cloud-CV/cvfy-frontend/blob/master/src/components/inputcomponents/ImageInput/SingleInput.js).

**Comment by AvaisP** [comment]
@tocttou Yes I had tried creating a file object but on calling the updateFormData and updateImage functions, it was giving me an error in the sense that it would write an empty fille with .png extension in the /tmp directory. I tried using the exact same line you posted 
```
const file = new File(['http://i.imgur.com/8lIYpog.png'], 'filename.png', { type: 'image/png' });
```
I am still facing the same error. Any idea on what I'm doing wrong?

**Comment by AvaisP** [comment]
![screenshot from 2017-03-17 02-19-13](https://cloud.githubusercontent.com/assets/15157205/24018146/b82080aa-0ab8-11e7-8d07-1981eef27cc4.png)
![screenshot from 2017-03-17 02-19-47](https://cloud.githubusercontent.com/assets/15157205/24018148/b8fbce8a-0ab8-11e7-861a-cbde6e2781c9.png)
![screenshot from 2017-03-17 02-19-53](https://cloud.githubusercontent.com/assets/15157205/24018149/ba177bc0-0ab8-11e7-974b-6213a585068a.png)

Hey. Upload from Dropbox is done. I'll just write the code in a better manner and send a pull request as soon as possible!

**Comment by AvaisP** [comment]
@dexter1691 @tocttou 
I've made the necessary changes in the code have made a local commit. Kindly merge #37 as soon as possible so that I can generate another pull request with code that supports uploading media from dropbox.

**Comment by AvaisP** [comment]
#38 has been merged. You can close the issue @dexter1691
